## Import NumPy

In [1]:
import numpy as np

## Create a numpy array from tuple and list

In [2]:
# Create a numpy array by passing tuple

n = np.array ((1, 2, 3, 4, 5))

print(f"Original array: {n}")

print (f'\ntype:', type(n))

Original array: [1 2 3 4 5]

type: <class 'numpy.ndarray'>


In [3]:
# Create a numpy array from a list

n = np.array ([1, 2, 3, 4, 5])

print(f"Original array: {n}")

print (f'\nType:', type(n))

Original array: [1 2 3 4 5]

Type: <class 'numpy.ndarray'>


## Create different dimensional arrays

### 0-D array

In [4]:
n = np.array (50)

print(f"Original array: {n}")

print (f'\nDimension of array: {n.ndim}')

Original array: 50

Dimension of array: 0


### 1-D array

In [5]:
n = np.array ([1, 2, 3, 4, 5])

print(f"Original array: {n}")

print (f'\nDimension of array: {n.ndim}')

Original array: [1 2 3 4 5]

Dimension of array: 1


### 2-D array

In [6]:
n = np.array ([[1, 2], [3, 4], [5, 6]])

print(f"Original array: \n{n}")

print (f'\nDimension of array: {n.ndim}')

Original array: 
[[1 2]
 [3 4]
 [5 6]]

Dimension of array: 2


#### 3-D array

In [7]:
n = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"Original array: \n{n}")

print (f'\nDimension of array: {n.ndim}')

Original array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimension of array: 3


## Initialize arrays with zeros

In [8]:
n = np.zeros((3, 4))

print(f"Original array: \n{n}")

print (f'\nDimension of array: {n.ndim}')

Original array: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Dimension of array: 2


## Numpy supports following data types
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string

In [9]:
n = np.array([1, 2, 3, 4])

print(f"Original array: {n}")

print (f'\nData type of array: {n.dtype}')

Original array: [1 2 3 4]

Data type of array: int64


In [10]:
n = np.array (["Andrew", "John", "Mary"])

print(f"Original array: {n}")

print (f'\nData type of array: {n.dtype}')

Original array: ['Andrew' 'John' 'Mary']

Data type of array: <U6


In [11]:
n = np.array (["Andrew", "John", "Mary"], dtype='S')

print(f"Original array: {n}")

print (f'\nData type of array: {n.dtype}')

Original array: [b'Andrew' b'John' b'Mary']

Data type of array: |S6


## Converting data type of array

In [12]:
n = np.array(["1", "2", "3", "4"])

print(f"Original array: {n}")

print (f'\nData type of array: {n.dtype}')

n = n.astype(int)

print(f"After convert to string to int : {n}")

print (f'Data type of array: {n.dtype}')

Original array: ['1' '2' '3' '4']

Data type of array: <U1
After convert to string to int : [1 2 3 4]
Data type of array: int64


## Accessing array elements with index ( 0 is the first index)

### Accessing elements of 1-D array

In [13]:
n = np.array(["1", "2", "3", "4"], dtype='int')

print(f"Original array: {n}")

print (f'\nElement at index 0: {n[0]} and data type: {n[0].dtype}')
print (f'Element at index 1: {n[1]} and data type: {n[1].dtype}')
print (f'Element at index 2: {n[2]} and data type: {n[2].dtype}')
print (f'Element at index 3: {n[3]} and data type: {n[3].dtype}')

Original array: [1 2 3 4]

Element at index 0: 1 and data type: int64
Element at index 1: 2 and data type: int64
Element at index 2: 3 and data type: int64
Element at index 3: 4 and data type: int64


### Accessing elements of 2-D array

In [14]:
n = np.array ([[1, 2], [3, 4], [5, 6]])

print(f"Original array: {n}")

print (f'\n\nFirst set {n[0]} and data type: {n[0].dtype}')
print (f'Second set {n[1]} and data type: {n[1].dtype}')
print (f'Third set {n[2]} and data type: {n[2].dtype}\n\n')

print (f'Element at row 0 and column 0: {n[0, 0]} and data type: {n[0, 0].dtype}')
print (f'Element at row 0 and column 1: {n[0, 1]} and data type: {n[0, 1].dtype}')
print (f'Element at row 1 and column 0: {n[1, 0]} and data type: {n[1, 0].dtype}')
print (f'Element at row 1 and column 1: {n[1, 1]} and data type: {n[1, 1].dtype}')
print (f'Element at row 2 and column 0: {n[2, 0]} and data type: {n[2, 0].dtype}')
print (f'Element at row 2 and column 1: {n[2, 1]} and data type: {n[2, 1].dtype}')

Original array: [[1 2]
 [3 4]
 [5 6]]


First set [1 2] and data type: int64
Second set [3 4] and data type: int64
Third set [5 6] and data type: int64


Element at row 0 and column 0: 1 and data type: int64
Element at row 0 and column 1: 2 and data type: int64
Element at row 1 and column 0: 3 and data type: int64
Element at row 1 and column 1: 4 and data type: int64
Element at row 2 and column 0: 5 and data type: int64
Element at row 2 and column 1: 6 and data type: int64


### Accessing elements of 3-D array

In [15]:
n = np.array([
                    [
                        [1, 2, 3],
                        [4, 5, 6]
                    ],
                    [
                        [7, 8, 9],
                        [10, 11, 12]
                    ]
                ])

print(f"Original array: \n{n}")

print (f'\n\nFirst depth {n[0]} and data type: {n[0].dtype}')
print (f'Second depth {n[1]} and data type: {n[1].dtype}\n\n')

print (f'First row of first depth {n[0, 0]} and data type: {n[0, 0].dtype}')
print (f'Second row of first depth {n[0, 1]} and data type: {n[0, 1].dtype}')
print (f'First row of second depth {n[1, 0]} and data type: {n[1, 0].dtype}')
print (f'Second row of second depth {n[1, 1]} and data type: {n[1, 1].dtype}\n\n')

print (f'Element at depth 0, row 0 and column 0: {n[0, 0, 0]} and data type: {n[0, 0, 0].dtype}')
print (f'Element at depth 0, row 0 and column 1: {n[0, 0, 1]} and data type: {n[0, 0, 1].dtype}')
print (f'Element at depth 0, row 0 and column 2: {n[0, 0, 2]} and data type: {n[0, 0, 2].dtype}')
print (f'Element at depth 0, row 1 and column 0: {n[0, 1, 0]} and data type: {n[0, 1, 0].dtype}')
print (f'Element at depth 0, row 1 and column 1: {n[0, 1, 1]} and data type: {n[0, 1, 1].dtype}')
print (f'Element at depth 0, row 1 and column 2: {n[0, 1, 2]} and data type: {n[0, 1, 2].dtype}')
print (f'Element at depth 1, row 0 and column 0: {n[1, 0, 0]} and data type: {n[1, 0, 0].dtype}')
print (f'Element at depth 1, row 0 and column 1: {n[1, 0, 1]} and data type: {n[1, 0, 1].dtype}')
print (f'Element at depth 1, row 0 and column 2: {n[1, 0, 2]} and data type: {n[1, 0, 2].dtype}')
print (f'Element at depth 1, row 1 and column 0: {n[1, 1, 0]} and data type: {n[1, 1, 0].dtype}')
print (f'Element at depth 1, row 1 and column 1: {n[1, 1, 1]} and data type: {n[1, 1, 1].dtype}')
print (f'Element at depth 1, row 1 and column 2: {n[1, 1, 2]} and data type: {n[1, 1, 2].dtype}')

Original array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


First depth [[1 2 3]
 [4 5 6]] and data type: int64
Second depth [[ 7  8  9]
 [10 11 12]] and data type: int64


First row of first depth [1 2 3] and data type: int64
Second row of first depth [4 5 6] and data type: int64
First row of second depth [7 8 9] and data type: int64
Second row of second depth [10 11 12] and data type: int64


Element at depth 0, row 0 and column 0: 1 and data type: int64
Element at depth 0, row 0 and column 1: 2 and data type: int64
Element at depth 0, row 0 and column 2: 3 and data type: int64
Element at depth 0, row 1 and column 0: 4 and data type: int64
Element at depth 0, row 1 and column 1: 5 and data type: int64
Element at depth 0, row 1 and column 2: 6 and data type: int64
Element at depth 1, row 0 and column 0: 7 and data type: int64
Element at depth 1, row 0 and column 1: 8 and data type: int64
Element at depth 1, row 0 and column 2: 9 and data type: int64
Element at depth 1, 

## Negative indexing (it starts from -1 and goes from right to left)

#### Negative indexing in 1-D array

In [16]:
n = np.array (["1", "2", "3", "4"], dtype='int')

print(f"Original array: {n}")

print (f'\nElement at index -1 (first from last element): {n[-1]} and data type: {n[-1].dtype}')
print (f'Element at index -2 (second from last element): {n[-2]} and data type: {n[-2].dtype}')
print (f'Element at index -3 (third from last element): {n[-3]} and data type: {n[-3].dtype}')
print (f'Element at index -4 (fourth from last element): {n[-4]} and data type: {n[-4].dtype}')

Original array: [1 2 3 4]

Element at index -1 (first from last element): 4 and data type: int64
Element at index -2 (second from last element): 3 and data type: int64
Element at index -3 (third from last element): 2 and data type: int64
Element at index -4 (fourth from last element): 1 and data type: int64


#### Negative indexing in 2-D array

In [17]:
n = np.array ([
                    [1, 2],
                    [3, 4],
                    [5, 6]
                ])

print(f"Original array: \n{n}")

print (f'\nElement at row -1 and column -1: {n[-1, -1]} and data type: {n[-1, -1].dtype}')
print (f'Element at row -1 and column -2: {n[-1, -2]} and data type: {n[-1, -2].dtype}')
print (f'Element at row -2 and column -1: {n[-2, -1]} and data type: {n[-2, -1].dtype}')
print (f'Element at row -2 and column -2: {n[-2, -2]} and data type: {n[-2, -2].dtype}')
print (f'Element at row -3 and column -1: {n[-3, -1]} and data type: {n[-3, -1].dtype}')
print (f'Element at row -3 and column -2: {n[-3, -2]} and data type: {n[-3, -2].dtype}')

Original array: 
[[1 2]
 [3 4]
 [5 6]]

Element at row -1 and column -1: 6 and data type: int64
Element at row -1 and column -2: 5 and data type: int64
Element at row -2 and column -1: 4 and data type: int64
Element at row -2 and column -2: 3 and data type: int64
Element at row -3 and column -1: 2 and data type: int64
Element at row -3 and column -2: 1 and data type: int64


## Slicing of arrays
### e.g. array[start:end:step] ( here start is inclusive and end is exclusive)

![<img src="./images/array-slicing.png" width="550" height="300](images/array-slicing.png)

In [18]:
# Slicing from 1 to 3 (3 is excluded)

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Original array: {n}")

s = n[1:3]
print (f'\nSliced array from index 1 to 3 (3 is excluded): {s}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sliced array from index 1 to 3 (3 is excluded): [20 30]


In [19]:
# Slicing from Index 2 to 5 (5 is excluded)

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {n}")

s = n[2:5]
print (f'\nSliced array from index 2 to 5 (5 is excluded): {s}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sliced array from index 2 to 5 (5 is excluded): [30 40 50]


In [20]:
# Slicing from index 5 to end

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {n}")

s = n[5:]
print (f'\nSliced array from index 5 to end: {s}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sliced array from index 5 to end: [ 60  70  80  90 100]


In [21]:
# Slicing from start to index 5 (5 is excluded)

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Original array: {n}")

s = n[:5]
print (f'\nSliced array from start to index 5 (5 is excluded): {s}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sliced array from start to index 5 (5 is excluded): [10 20 30 40 50]


In [22]:
# Slicing with step for 1D array

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Original array: {n}")

s = n[1:10:2]
print (f'\nSliced array from index 1 to 10 with step 2: {s}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Sliced array from index 1 to 10 with step 2: [ 20  40  60  80 100]


In [23]:
# Slicing with step for 2D array

n = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
              [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

print(f"Original array: \n{n}")

s = n[0, 2:5]
print (f'\nSliced array from row 0 and index 2 to 5: {s}')

Original array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Sliced array from row 0 and index 2 to 5: [3 4 5]


In [24]:
# Slicing for both the dimensions in 2D array

n = np.array ([
                    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
                    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
                    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
                ])

print(f"Original array: \n{n}")

s = n[0:2, 2:5]

print (f'\nSliced array from row 0 to 2 and index 2 to 5: \n{s}')

Original array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Sliced array from row 0 to 2 and index 2 to 5: 
[[ 3  4  5]
 [13 14 15]]


## Array Shape

In [25]:
# Check the shape of a 0-D array

n = np.array (10)

print(f"Original array: {n}")

print(f'\nDimension of array: {n.ndim}')
print (f'Shape of array: {n.shape}')

Original array: 10

Dimension of array: 0
Shape of array: ()


In [26]:
# Check the shape of a 1-D array

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {n}")

print(f'\nDimension of array: {n.ndim}')
print (f'Shape of array: {n.shape}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Dimension of array: 1
Shape of array: (10,)


In [27]:
# Check the shape of a 2-D array

n = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
              [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

print(f"Original array: \n{n}")

print(f'\nDimension of array: {n.ndim}')
print (f'Shape of array: {n.shape}')


Original array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Dimension of array: 2
Shape of array: (5, 10)


In [28]:
# Check the shape of a 3-D array

n = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6]
                ],
                [
                    [7, 8, 9],
                    [10, 11, 12]
                ]
            ])
print(f"Original array: \n{n}")

print(f'\nDimension of array: {n.ndim}')
print (f'Shape of array: {n.shape}')

Original array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimension of array: 3
Shape of array: (2, 2, 3)


## Reshaping of arrays

In [29]:
# Reshape the array

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Original array: {n}")
print(f'\nOriginal shape of array: {n.shape}')

resarr = n.reshape(2, 5)

print(f'\nReshaped array: \n{resarr}')
print(f'\nReshaped shape of array: {resarr.shape}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Original shape of array: (10,)

Reshaped array: 
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

Reshaped shape of array: (2, 5)


In [30]:
# Convert 3-D array into 1-D array

n = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6]
                ],
                [
                    [7, 8, 9],
                    [10, 11, 12]
                ]
            ])

print(f"Original array: \n{n}")
print(f'\nOriginal dim of array: {n.ndim}')
print(f'Original shape of array: {n.shape}')

resarr = n.reshape(-1)
print(f'Reshaped array: {resarr}')
print(f'Reshaped shape of array: {resarr.shape}')

Original array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Original dim of array: 3
Original shape of array: (2, 2, 3)
Reshaped array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped shape of array: (12,)


## Iterating arrays

In [31]:
n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Original array: {n}")

print(f"\nIterating 1-D array:")
for i in n:
    print(i)

print(f"\nType of each element: {n[0].dtype}")
print(f"Data type: {type(n.dtype)}")
print(f"Dimension of array: {n.ndim}")

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Iterating 1-D array:
10
20
30
40
50
60
70
80
90
100

Type of each element: int64
Data type: <class 'numpy.dtypes.Int64DType'>
Dimension of array: 1


In [32]:
# Iterating 2-D array
n = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
              [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

print(f"Original array: \n{n}")

print(f"\nIterating 2-D array:")

for index, i,  in enumerate(n):
    print(f'Row {index}: {i}')
    for j in i:
        print(j)

print(f"\nType of each element: {n[0,0].dtype}")
print(f"Data type: {type(n.dtype)}")
print(f"Dimension of array: {n.ndim}")

Original array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Iterating 2-D array:
Row 0: [ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
Row 1: [11 12 13 14 15 16 17 18 19 20]
11
12
13
14
15
16
17
18
19
20
Row 2: [21 22 23 24 25 26 27 28 29 30]
21
22
23
24
25
26
27
28
29
30
Row 3: [31 32 33 34 35 36 37 38 39 40]
31
32
33
34
35
36
37
38
39
40
Row 4: [41 42 43 44 45 46 47 48 49 50]
41
42
43
44
45
46
47
48
49
50

Type of each element: int64
Data type: <class 'numpy.dtypes.Int64DType'>
Dimension of array: 2


In [33]:
# Iterating 3-D array
n = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6]
                ],
                [
                    [7, 8, 9],
                    [10, 11, 12]
                ]
            ])

print(f"Original array: \n{n}")

for index, i in enumerate(n):
    print(f'\nDepth {index}: \n  {i}')
    for j in i:
        print(f' \n    Row {index}: {j}')
        for k in j:
            print(f"     {k}")

print(f"\nType of each element: {n[0,0,0].dtype}")
print(f"Data type: {type(n.dtype)}")

Original array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Depth 0: 
  [[1 2 3]
 [4 5 6]]
 
    Row 0: [1 2 3]
     1
     2
     3
 
    Row 0: [4 5 6]
     4
     5
     6

Depth 1: 
  [[ 7  8  9]
 [10 11 12]]
 
    Row 1: [7 8 9]
     7
     8
     9
 
    Row 1: [10 11 12]
     10
     11
     12

Type of each element: int64
Data type: <class 'numpy.dtypes.Int64DType'>


## Joining of arrays

### Joining using concatenate(), stack(), hstack(), vstack(), dstack() and column_stack() functions

#### Joining using concatenate(arrays, axis=0, out=None, *, dtype=None, casting='same_kind') for 1-D arrays
![<img src="./images/array-1d-concatenate.png" width="550" height="300](images/array-1d-concatenate.png)


In [34]:
# Joining 1-D 2 arrays using concatenate() function as shown in above image

n1 = np.array ([1, 2, 3])
n2 = np.array ([4, 5, 6])

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.concatenate((n1, n2))
print(f'\nConcatenated array: {n3}')
print(f'\nDimension of array: {n3.ndim}')


First array: [1 2 3]
Second array: [4 5 6]

Concatenated array: [1 2 3 4 5 6]

Dimension of array: 1


In [35]:
# Joining 1-D 3 arrays using concatenate() function

n1 = np.array ([1, 2, 3])
n2 = np.array ([4, 5, 6])
n3 = np.array ([7, 8, 9])

print(f"First array: {n1}")
print(f"Second array: {n2}")
print(f"Third array: {n3}")

n4 = np.concatenate((n1, n2, n3))

print(f'Concatenated array: {n4}')
print(f'Dimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: [1 2 3]
Second array: [4 5 6]
Third array: [7 8 9]
Concatenated array: [1 2 3 4 5 6 7 8 9]
Dimension of array: 1
Shape of array: (9,)


##### Joining using concatenate(a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind") for 2-D arrays
![<img src="./images/array-2d-concatenate.png" width="550" height="300](images/array-2d-concatenate.png)

In [36]:
# Joining 1-D arrays using concatenate() function as shown in above image

n1 = np.array ([[1, 2], [3, 4]])
n2 = np.array ([[5, 6], [7, 8]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
n3 = np.concatenate((n1, n2))
print(f'\nConcatenated array with axis 0: \n{n3}')

n4 = np.concatenate((n1, n2), axis=1)  # axis 1 will have no effect on 1-D array
print(f'\nConcatenated array with axis 1: \n{n4}')

First array: 
[[1 2]
 [3 4]]

Second array: 
[[5 6]
 [7 8]]

Concatenated array with axis 0: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array with axis 1: 
[[1 2 5 6]
 [3 4 7 8]]


#### Joining using stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind') functions of 1-D arrays
![<img src="./images/array-1d-stack.png"](images/array-1d-stack.png)

![<img src="./images/array-1d-stack-with-axis.png"](images/array-1d-stack-with-axis.png)

In [37]:
# Joining 1-D 2 arrays using stack() function as shown in above image
n1 = np.array ([1, 2])
n2 = np.array ([3, 4])

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.stack((n1, n2))
print(f'\nStacked array: \n   {n3}')
print(f'\nDimension of array: {n3.ndim}')

n4 = np.stack((n1, n2), axis=1)
print(f'\nStacked array with axis 1: \n   {n4}')

First array: [1 2]
Second array: [3 4]

Stacked array: 
   [[1 2]
 [3 4]]

Dimension of array: 2

Stacked array with axis 1: 
   [[1 3]
 [2 4]]


In [38]:
# Joining 2-D 3 arrays using stack() function

n1 = np.array ([[1, 2, 3], [4, 5, 6]])
n2 = np.array ([[7, 8, 9], [10, 11, 12]])
n3 = np.array ([[13, 14, 15], [16, 17, 18]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
print(f"\nThird array: \n{n3}")

n4 = np.stack((n1, n2, n3))
print(f'\nStacked array: \n   {n4}')
print(f'\nDimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: 
[[1 2 3]
 [4 5 6]]

Second array: 
[[ 7  8  9]
 [10 11 12]]

Third array: 
[[13 14 15]
 [16 17 18]]

Stacked array: 
   [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Dimension of array: 3
Shape of array: (3, 2, 3)


#### Joining using hstack(tup, *, dtype=None, casting='same_kind') functions of 1-D arrays
![<img src="./images/array-1d-hstack.png"](images/array-1d-hstack.png)

In [39]:
# Joining 1-D 2 arrays using hstack() function as shown in above image

n1 = np.array ([[1, 3], [2, 4]])
n2 = np.array ([[0, 0], [1, 1]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")

n3 = np.hstack((n1, n2))
print(f'\nHorizontally stacked array: \n{n3}')
print(f'\nDimension of array: {n3.ndim}')

First array: 
[[1 3]
 [2 4]]

Second array: 
[[0 0]
 [1 1]]

Horizontally stacked array: 
[[1 3 0 0]
 [2 4 1 1]]

Dimension of array: 2


In [40]:
# Joining 2-D arrays using hstack() function

n1 = np.array ([[1, 2, 3], [4, 5, 6]])
n2 = np.array ([[7, 8, 9], [10, 11, 12]])
n3 = np.array ([[13, 14, 15], [16, 17, 18]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
print(f"\nThird array: \n{n3}")

n4 = np.hstack((n1, n2, n3))
print(f'\nHorizontally stacked array: \n{n4}')
print(f'\nDimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: 
[[1 2 3]
 [4 5 6]]

Second array: 
[[ 7  8  9]
 [10 11 12]]

Third array: 
[[13 14 15]
 [16 17 18]]

Horizontally stacked array: 
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]

Dimension of array: 2
Shape of array: (2, 9)


#### Joining using dstack(tup) functions of 1-D arrays
![<img src="./images/array-1d-dstack.png"](images/array-1d-dstack.png)

In [41]:
# Joining 1-D 2 arrays using dstack() function as shown in above image
n1 = np.array ([3, 5, 7])
n2 = np.array ([5, 7, 9])

print(f"First array: {n1}")
print(f"\nSecond array: {n2}")
n3 = np.dstack((n1, n2))
print(f'\nDepth stacked array: \n{n3}')
print(f'\nDimension of array: {n3.ndim}')

First array: [3 5 7]

Second array: [5 7 9]

Depth stacked array: 
[[[3 5]
  [5 7]
  [7 9]]]

Dimension of array: 3


#### Joining using vstack(tup, *, dtype=None, casting='same_kind') functions of 2D arrays
![<img src="./images/array-1d-vstack.png"](images/array-1d-vstack.png)

In [42]:
# Joining 1-D 2 arrays using vstack() function as shown in above image

n1 = np.array ([[1, 1], [0, 0]])
n2 = np.array ([[0, 1], [1, 0]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")

n3 = np.vstack((n1, n2))
print(f'\nVertically stacked array: \n{n3}')

print(f"\nDimension of 1st array: {n2.ndim}")
print(f"\nDimension of 2nd array: {n2.ndim}")

print(f'Dimension of array: {n3.ndim}')

First array: 
[[1 1]
 [0 0]]

Second array: 
[[0 1]
 [1 0]]

Vertically stacked array: 
[[1 1]
 [0 0]
 [0 1]
 [1 0]]

Dimension of 1st array: 2

Dimension of 2nd array: 2
Dimension of array: 2


In [43]:
# Joining 2-D arrays using vstack() function
n1 = np.array ([[1, 2, 3], [4, 5, 6]])
n2 = np.array ([[7, 8, 9], [10, 11, 12]])
n3 = np.array ([[13, 14, 15], [16, 17, 18]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
print(f"\nThird array: \n{n3}")

n4 = np.vstack((n1, n2, n3))
print(f'\nVertically stacked array: \n{n4}')
print(f'\nDimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: 
[[1 2 3]
 [4 5 6]]

Second array: 
[[ 7  8  9]
 [10 11 12]]

Third array: 
[[13 14 15]
 [16 17 18]]

Vertically stacked array: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Dimension of array: 2
Shape of array: (6, 3)


In [44]:
# Joining 2-D arrays using dstack() function
n1 = np.array ([[1, 2, 3], [4, 5, 6]])
n2 = np.array ([[7, 8, 9], [10, 11, 12]])
n3 = np.array ([[13, 14, 15], [16, 17, 18]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
print(f"\nThird array: \n{n3}")

n4 = np.dstack((n1, n2, n3))
print(f'\nDepth stacked array: \n{n4}')
print(f'\nDimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: 
[[1 2 3]
 [4 5 6]]

Second array: 
[[ 7  8  9]
 [10 11 12]]

Third array: 
[[13 14 15]
 [16 17 18]]

Depth stacked array: 
[[[ 1  7 13]
  [ 2  8 14]
  [ 3  9 15]]

 [[ 4 10 16]
  [ 5 11 17]
  [ 6 12 18]]]

Dimension of array: 3
Shape of array: (2, 3, 3)


#### Joining using column_stack(tup) functions of 1-D arrays
![<img src="./images/array-1d-column-stack.png"](images/array-1d-column-stack.png)

In [45]:
# Joining 1-D 2 arrays using column_stack() function as shown in above image
n1 = np.array ([1, 2, 3])
n2 = np.array ([2, 3, 4])

print(f"First array: {n1}")
print(f"\nSecond array: {n2}")
n3 = np.column_stack((n1, n2))
print(f'\nColumn stacked array: \n{n3}')
print(f'\nDimension of array: {n3.ndim}')

n4 = np.dstack((n1, n2))
print(f"\nDepth stacked array: \n{n4}")
print(f'\nDimension of array: {n4.ndim}')

n5 = np.vstack((n1, n2))
print(f"\nVertically stacked array: \n{n5}")
print(f'\nDimension of array: {n5.ndim}')

First array: [1 2 3]

Second array: [2 3 4]

Column stacked array: 
[[1 2]
 [2 3]
 [3 4]]

Dimension of array: 2

Depth stacked array: 
[[[1 2]
  [2 3]
  [3 4]]]

Dimension of array: 3

Vertically stacked array: 
[[1 2 3]
 [2 3 4]]

Dimension of array: 2


In [46]:
# Joining 2-D arrays using column_stack() function

n1 = np.array ([[1, 2, 3], [4, 5, 6]])
n2 = np.array ([[7, 8, 9], [10, 11, 12]])
n3 = np.array ([[13, 14, 15], [16, 17, 18]])

print(f"First array: \n{n1}")
print(f"\nSecond array: \n{n2}")
print(f"\nThird array: \n{n3}")

n4 = np.column_stack((n1, n2, n3))
print(f'\nColumn stacked array: \n{n4}')
print(f'\nDimension of array: {n4.ndim}')
print(f'Shape of array: {n4.shape}')

First array: 
[[1 2 3]
 [4 5 6]]

Second array: 
[[ 7  8  9]
 [10 11 12]]

Third array: 
[[13 14 15]
 [16 17 18]]

Column stacked array: 
[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]

Dimension of array: 2
Shape of array: (2, 9)


## Splitting of arrays

#### Splitting using array_split(ary, indices_or_sections, axis=0) function

In [47]:
# Splitting 1-D array using array_split() function

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {n}")

n1, n2, n3 = np.array_split(n, 3)
print('\nAfter splitting: 1st array:', n1)
print('After splitting: 2nd array:', n2)
print('After splitting: 3rd array:', n3)

print(f'\nDimension of 1st array: {n1.ndim}')
print(f'Shape of 1st array: {n1.shape}')
print(f"Data type of 1st array: {n1.dtype}")

print(f'\nDimension of 2nd array: {n2.ndim}')
print(f'Shape of 2nd array: {n2.shape}')
print(f"Data type of 2nd array: {n2.dtype}")

print(f'\nDimension of 3rd array: {n3.ndim}')
print(f'Shape of 3rd array: {n3.shape}')
print(f"Data type of 3rd array: {n3.dtype}")

Original array: [ 10  20  30  40  50  60  70  80  90 100]

After splitting: 1st array: [10 20 30 40]
After splitting: 2nd array: [50 60 70]
After splitting: 3rd array: [ 80  90 100]

Dimension of 1st array: 1
Shape of 1st array: (4,)
Data type of 1st array: int64

Dimension of 2nd array: 1
Shape of 2nd array: (3,)
Data type of 2nd array: int64

Dimension of 3rd array: 1
Shape of 3rd array: (3,)
Data type of 3rd array: int64


In [48]:
# Splitting 2-D array using array_split() function

n = np.array ([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
              [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

print(f"Original array: \n{n}")

n1, n2 = np.array_split(n, 2)

print(f'\nAfter Split 1st array: \n{n1}')
print(f'\nAfter Split 2nd array: \n{n2}')

print(f'\nDimension of 1st array: {n1.ndim}')
print(f'Shape of 1st array: {n1.shape}')
print(f"Data type of 1st array: {n1.dtype}")

print(f'\nDimension of 2nd array: {n2.ndim}')
print(f"Shape of 2nd array: {n2.shape}")
print(f"Data type of 2nd array: {n2.dtype}")

Original array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

After Split 1st array: 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

After Split 2nd array: 
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]

Dimension of 1st array: 2
Shape of 1st array: (3, 10)
Data type of 1st array: int64

Dimension of 2nd array: 2
Shape of 2nd array: (2, 10)
Data type of 2nd array: int64


## Search Array

In [49]:
# Search in 1-D array using np.where() function

n = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(f"Original array: {n}")

result = np.where(n < 50)
print(f'\nIndex of elements less than 50: {result}')

result = np.where(n == 50)
print(f'\nIndex of elements equal to 50: {result}')

result = np.where(n > 50)
print(f'\nIndex of elements greater than 50: {result}')

Original array: [ 10  20  30  40  50  60  70  80  90 100]

Index of elements less than 50: (array([0, 1, 2, 3]),)

Index of elements equal to 50: (array([4]),)

Index of elements greater than 50: (array([5, 6, 7, 8, 9]),)


## Sorting of array

In [50]:
# Generate random 1-D array and sort it using np.sort() function

n = np.random.randint(1, 100, 10)
print(f"Original array: {n}")

s = np.sort(n)
print(f'\nSorted array: {s}')

Original array: [78 14 91 68 38 74 33 76 63 50]

Sorted array: [14 33 38 50 63 68 74 76 78 91]


In [51]:
# Generate random string array and sort it using np.sort() function

n = np.array (['John', 'Alice', 'Bob', 'Charlie', 'David'])
print(f"Original array: {n}")

s = np.sort(n)
print(f'\nSorted array: {s}')

Original array: ['John' 'Alice' 'Bob' 'Charlie' 'David']

Sorted array: ['Alice' 'Bob' 'Charlie' 'David' 'John']


In [52]:
# Generate random 2-D array and sort it using np.sort() function

n = np.random.randint(1, 100, (3, 4))
print(f"Original array: \n{n}")

s = np.sort(n)
print(f'\nSorted array: \n{s}')

Original array: 
[[76 47 34 25]
 [17 79 34 60]
 [57 36 72 52]]

Sorted array: 
[[25 34 47 76]
 [17 34 60 79]
 [36 52 57 72]]


## Axis in numpy ( Axis 0 is for rows and Axis 1 is for columns)

In [53]:
# Get max value in randon generated 2-D (2 X 2) array along axis 0 and axis 1

n = np.random.randint(1, 100, (2, 2))

print(f"Original array: \n{n}")

max_axis0 = np.max(n, axis=0)

print(f'\nMax value along axis 0: {max_axis0}')

max_axis1 = np.max(n, axis=1)

print(f'\nMax value along axis 1: {max_axis1}')

Original array: 
[[78 97]
 [75 22]]

Max value along axis 0: [78 97]

Max value along axis 1: [97 75]


In [54]:
# Get max value in randon generated 2-D (3 X 4) array along axis 0 and axis 1

n = np.random.randint(1, 100, (3, 4))
print(f"Original array: \n{n}")

max_axis0 = np.max(n, axis=0)
print(f'\nMax value along axis 0: {max_axis0}')

max_axis1 = np.max(n, axis=1)
print(f'\nMax value along axis 1: {max_axis1}')


Original array: 
[[74 20 74 19]
 [39  7 22  4]
 [74  1 29 98]]

Max value along axis 0: [74 20 74 98]

Max value along axis 1: [74 39 98]


In [55]:
# Get min value in randon generated 2-D (2 X 2) array along axis 0 and axis 1

n = np.random.randint(1, 100, (2, 2))
print(f"Original array: \n{n}")

min_axis0 = np.min(n, axis=0)

print(f'\nMin value along axis 0: {min_axis0}')

min_axis1 = np.min(n, axis=1)

print(f'\nMin value along axis 1: {min_axis1}')


Original array: 
[[96 16]
 [17 83]]

Min value along axis 0: [17 16]

Min value along axis 1: [16 17]


In [56]:
# Get max value in randon generated 2-D (3 X 4) array along axis 0 and axis 1

n = np.random.randint(1, 100, (3, 4))

print(f"Original array: \n{n}")

min_axis0 = np.min(n, axis=0)
print(f'\nMin value along axis 0: {min_axis0}')

min_axis1 = np.min(n, axis=1)
print(f'\nMin value along axis 1: {min_axis1}')

Original array: 
[[22  6 11 64]
 [75 14  1 76]
 [48 33 25 55]]

Min value along axis 0: [22  6  1 55]

Min value along axis 1: [ 6  1 25]


## Intersection of arrays ( common values in two arrays)

In [57]:
# Intersection of two  random generated 1-D sorted arrays using np.intersect1d() function

n1 = np.sort(np.random.randint(1, 20, 10))
n2 = np.sort(np.random.randint(1, 20, 10))

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.intersect1d(n1, n2)
print(f'\nIntersection of two arrays: {n3}')
print(f'\nDimension of array: {n3.ndim}')

First array: [ 1  5  7  8  8  9 11 15 15 18]
Second array: [ 1  5  8 11 13 14 17 17 19 19]

Intersection of two arrays: [ 1  5  8 11]

Dimension of array: 1


In [58]:
# Intersection of two  random generated 1-D unsorted arrays using np.intersect1d() function

n1 = np.random.randint(1, 20, 10)
n2 = np.random.randint(1, 20, 10)

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.intersect1d(n1, n2)
print(f'\nIntersection of two arrays: {n3}')

print(f'\nDimension of array: {n3.ndim}')

First array: [10 17 10 17  3  7  1  3 13  2]
Second array: [12 15  9 19  7  7  3  9  9 12]

Intersection of two arrays: [3 7]

Dimension of array: 1


In [59]:
# Intersection of two  random generated 1-D sorted arrays without common values using np.intersect1d() function

n1 = np.array([1, 3, 5, 7, 9])
n2 = np.array([2, 4, 6, 8, 10])

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.intersect1d(n1, n2)

print(f'\nIntersection of two arrays: {n3}')
print(f'\nDimension of array: {n3.ndim}')

First array: [1 3 5 7 9]
Second array: [ 2  4  6  8 10]

Intersection of two arrays: []

Dimension of array: 1


## Difference of arrays ( values in first array but not in second array)

In [60]:
# Difference of two  random generated 1-D sorted arrays using np.setdiff1d() function

n1 = np.sort(np.random.randint(1, 20, 10))
n2 = np.sort(np.random.randint(1, 20, 10))
print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.setdiff1d(n1, n2)

print(f'\nDifference of two arrays (values in first array but not in second array): {n3}')

print(f'\nDimension of array: {n3.ndim}')

First array: [ 2  3  5  7  8  9 12 14 17 18]
Second array: [ 3  4  5  5  6  6 14 14 15 18]

Difference of two arrays (values in first array but not in second array): [ 2  7  8  9 12 17]

Dimension of array: 1


## Operations on arrays

### Sum of arrays ( addition of two arrays along axis)

In [61]:
# Sum of two random generated 1-D arrays using np.sum() function along axis

n1 = np.random.randint(1, 20, 3)
n2 = np.random.randint(1, 20, 3)

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.sum([n1, n2], axis=0)

print(f'\nSum of two arrays with axis 9: {n3}')

n4 = np.sum([n1, n2], axis=1)

print(f'\nSum of two arrays with axis 1: {n4}')

First array: [12 12 17]
Second array: [16 17 16]

Sum of two arrays with axis 9: [28 29 33]

Sum of two arrays with axis 1: [41 49]


### Subtraction of arrays ( subtraction of two arrays, no axis )

In [62]:
# Subtraction of two random generated 1-D arrays using np.subtract() function

n1 = np.random.randint(1, 20, 3)
n2 = np.random.randint(1, 20, 3)

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.subtract(n1, n2)

print(f'\nSubtraction of two arrays: {n3}')


First array: [15  3 15]
Second array: [11 13  6]

Subtraction of two arrays: [  4 -10   9]


### Multiplication of arrays ( multiplication of two arrays NO axis)

In [63]:
# Multiplication of two random generated 1-D arrays using np.multiply() function along axis

n1 = np.random.randint(1, 20, 3)
n2 = np.random.randint(1, 20, 3)

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.multiply(n1, n2)

print(f'\nMultiplication of two arrays: {n3}')

First array: [ 8 10 10]
Second array: [15 11  2]

Multiplication of two arrays: [120 110  20]


### Division of arrays ( division of two arrays NO axis)

In [64]:
# Division of two random generated even numbers elements 1-D arrays using np.divide()

n1 = np.random.randint(2, 20, 3)*2
n2 = np.random.randint(1, 10, 3)*2

print(f"First array: {n1}")
print(f"Second array: {n2}")

n3 = np.divide(n1, n2)

print(f'\nDivision of two arrays: {n3}')

First array: [18 32 26]
Second array: [ 4 14 14]

Division of two arrays: [4.5        2.28571429 1.85714286]


## Scalar operations on arrays

### Addition of scalar to array

In [65]:
# Addition of scalar to random generated 1-D array using + operator
n = np.random.randint(1, 20, 5)
print(f"Original array: {n}")

s = n + 5

print(f'\nArray after addition of scalar 5: {s}')

Original array: [ 2  4 11 11 19]

Array after addition of scalar 5: [ 7  9 16 16 24]


### Subtraction of scalar from array

In [66]:
# Subtraction of scalar from random generated 1-D array using - operator

n = np.random.randint(1, 20, 5)
print(f"Original array: {n}")

s = n - 5

print(f'\nArray after subtraction of scalar 5: {s}')

Original array: [ 7  3 16 10  7]

Array after subtraction of scalar 5: [ 2 -2 11  5  2]


### Multiplication of array with scalar

In [67]:
# Multiplication of random generated 1-D array with scalar using * operator

n = np.random.randint(1, 20, 5)
print(f"Original array: {n}")

s = n * 10

print(f'\nArray after multiplication with scalar 10: {s}')

Original array: [15  5  2 17 13]

Array after multiplication with scalar 10: [150  50  20 170 130]


### Division of array with scalar

In [68]:
# Division of random generated even numbers elements 1-D array with scalar using / operator

n = np.random.randint(1, 20, 5)*2

print(f"Original array: {n}")

s = n / 2

print(f'\nArray after division with scalar 2: {s}')

Original array: [20  6 28 12 30]

Array after division with scalar 2: [10.  3. 14.  6. 15.]


## Statistical operations on arrays

### Mean of array ( average of all values in array)
$$ \bar{x} = \frac{\sum_{i=1}^{n} x_i}{n} $$

In [69]:
# Mean of random generated 1-D array using np.mean() function

n = np.sort(np.random.randint(1, 20, 5))
print(f"Original array: {n}")

m = np.mean(n)

print(f'\nMean of array: {m}')

Original array: [ 2  2  6 11 11]

Mean of array: 6.4


### Median of array ( middle value in sorted array)

If $n$ is odd, the median is the value at position $\frac{n+1}{2}$

If $n$ is even, the median can be calculated as:
$$ \text{Median} = \frac{x_{n/2} + x_{(n/2)+1}}{2} $$

In [70]:
# Median of random generated 1-D array using np.median() function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")
m = np.median(n)

print(f'\nMedian of array: {m}')

Original array: [15 13  9 17  3]

Median of array: 13.0


### Standard Deviation of array ( spread of values in array)

$$ \sigma = \sqrt{\frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}} $$

In [71]:
# Standard Deviation of random generated 1-D array using np.std() function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")

s = np.std(n)

print(f'\nStandard Deviation of array: {s}')

Original array: [ 5  5  6 19 15]

Standard Deviation of array: 5.865151319446072


### Variance of array ( average of squared differences from the mean)

$$ \sigma^2 = \frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N} $$

$$ s^2 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n-1} $$

In [72]:
# Intersection of two  random generated 1-D sorted arrays using np.intersect1d() function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")

v = np.var(n)

print(f'\nVariance of array: {v}')

Original array: [15  7  3 18  7]

Variance of array: 31.2


## Logarithm of array ( log to the base e of each element in array)

### Natural Logarithm (base e)

In [73]:
# Logarithm of random generated 1-D array using np.log() function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")

l = np.log(n)

print(f'\nLogarithm of array: {l}')

Original array: [19  6 12 19  2]

Logarithm of array: [2.94443898 1.79175947 2.48490665 2.94443898 0.69314718]


### Logarithm to base 10

In [74]:
# Logarithm to base 10 of random generated 1-D array using np.log10 function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")

l = np.log10(n)

print(f'\nLogarithm to base 10 of array: {l}')

Original array: [ 9 14  8 16  9]

Logarithm to base 10 of array: [0.95424251 1.14612804 0.90308999 1.20411998 0.95424251]


### Logarithm to base 2

In [75]:
# Logarithm to base 2 of random generated 1-D array using np.log2 function

n = np.random.randint(1, 20, 5)

print(f"Original array: {n}")

l = np.log2(n)

print(f'\nLogarithm to base 2 of array: {l}')

Original array: [16 19 19 13 12]

Logarithm to base 2 of array: [4.         4.24792751 4.24792751 3.70043972 3.5849625 ]


## LCM and GCD of two arrays

### LCM of two arrays

In [76]:
# LCM of two random generated 1-D arrays using np.lcm() function

n1 = np.random.randint(1, 10, 5)

n2 = np.random.randint(1, 10, 5)

print(f"First array: {n1}")
print(f"Second array: {n2}")

l = np.lcm(n1, n2)

print(f'\nLCM of two arrays: {l}')

First array: [7 5 7 7 3]
Second array: [8 9 5 6 1]

LCM of two arrays: [56 45 35 42  3]


### GCD of two arrays

In [77]:
# GCD of two random generated 1-D arrays using np.gcd() function

n1 = np.random.randint(1, 10, 5)
n2 = np.random.randint(1, 10, 5)

print(f"First array: {n1}")
print(f"Second array: {n2}")

g = np.gcd(n1, n2)

print(f'\nGCD of two arrays: {g}')

First array: [7 5 9 9 6]
Second array: [1 5 1 6 5]

GCD of two arrays: [1 5 1 3 1]
